import { Dispatch, FormEvent, SetStateAction } from "react";
import { ArrowUpRight, Check, Clock3, Heart } from "lucide-react";
import { ReservationForm, Treatment } from "../data";

type ReservationSectionProps = { readonly booked: boolean; readonly form: ReservationForm; readonly treatments: Treatment[]; readonly onChange: Dispatch<SetStateAction<ReservationForm>>; readonly onSubmit: (event: FormEvent<HTMLFormElement>) => void };

export function ReservationSection({ booked, form, treatments, onChange, onSubmit }: Readonly<ReservationSectionProps>) {
    return <section id="reservation" className="px-5 py-24 lg:py-32"><div className="mx-auto grid max-w-7xl gap-14 lg:grid-cols-[.75fr_1.25fr]"><div><p className="mb-4 text-xs font-semibold uppercase tracking-[.2em] text-sage">Votre rendez-vous</p><h2 className="font-display text-5xl leading-none sm:text-6xl">Réservez votre<br /><i>moment.</i></h2><p className="mt-6 max-w-md text-sm leading-7 text-black/60">Choisissez votre rituel et vos préférences. Nous vous confirmerons votre demande par email.</p><div className="mt-10 space-y-4 text-sm"><div><Clock3 className="mr-3 inline h-4 w-4" />Du lundi au samedi · 9h — 19h</div><div><Heart className="mr-3 inline h-4 w-4" />Cabine privative · adresse à personnaliser</div></div></div>
        <form onSubmit={onSubmit} className="rounded-[2rem] bg-white p-6 shadow-xl shadow-black/5 sm:p-9">{booked && <div className="mb-6 rounded-2xl bg-[#e5eee1] p-4 text-sm"><Check className="mr-2 inline h-4 w-4" />Votre demande est bien envoyée. Nous revenons vers vous rapidement.</div>}<div className="grid gap-5 sm:grid-cols-2">
            <label className="text-sm">Nom et prénom<input required value={form.name} onChange={event => onChange({ ...form, name: event.target.value })} className="mt-2 w-full rounded-xl bg-cream px-4 py-3 outline-none ring-0" placeholder="Votre nom" /></label>
            <label className="text-sm">Email<input required type="email" value={form.email} onChange={event => onChange({ ...form, email: event.target.value })} className="mt-2 w-full rounded-xl bg-cream px-4 py-3" placeholder="vous@email.fr" /></label>
            <label className="text-sm">Téléphone<input value={form.phone} onChange={event => onChange({ ...form, phone: event.target.value })} className="mt-2 w-full rounded-xl bg-cream px-4 py-3" placeholder="06 00 00 00 00" /></label>
            <label className="text-sm">Rituel<select value={form.treatment} onChange={event => onChange({ ...form, treatment: event.target.value })} className="mt-2 w-full rounded-xl bg-cream px-4 py-3">{treatments.map(treatment => <option key={treatment.title}>{treatment.title}</option>)}</select></label>
            <label className="text-sm">Date souhaitée<input required type="date" value={form.date} onChange={event => onChange({ ...form, date: event.target.value })} className="mt-2 w-full rounded-xl bg-cream px-4 py-3" /></label>
            <label className="text-sm">Créneau souhaité<select required value={form.time} onChange={event => onChange({ ...form, time: event.target.value })} className="mt-2 w-full rounded-xl bg-cream px-4 py-3"><option value="">Choisir</option>{["09:00", "10:30", "12:00", "14:00", "15:30", "17:00", "18:00"].map(time => <option key={time}>{time}</option>)}</select></label>
        </div><label className="mt-5 block text-sm">Message (optionnel)<textarea value={form.message} onChange={event => onChange({ ...form, message: event.target.value })} rows={3} className="mt-2 w-full rounded-xl bg-cream px-4 py-3" placeholder="Une demande particulière ?" /></label><input aria-hidden tabIndex={-1} autoComplete="off" value={form.website} onChange={event => onChange({ ...form, website: event.target.value })} className="absolute -left-[9999px]" /><label className="mt-5 flex gap-3 text-xs leading-5 text-black/55"><input required type="checkbox" className="mt-1" />J’accepte que mes informations soient utilisées pour traiter ma demande de réservation.</label><button type="submit" className="mt-7 w-full rounded-full bg-ink py-4 text-sm font-semibold text-white transition hover:-translate-y-0.5">Envoyer ma demande <ArrowUpRight className="ml-1 inline h-4 w-4" /></button><p className="mt-3 text-center text-xs text-black/40">La réservation est confirmée après validation par la maison.</p></form>
    </div></section>;
}